### ISSUE TITLE
SEO checker - Social preview

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#16]
I believe the SEO Checker social preview is better than the functionality we put in last night. Especially for campaigns.

Please can we either:
**Reinstate the SEO Checker functionality**
or
**Remove the social preview tab from the document type composition**

**Comment by catiarodriguescosta** [comment]
One of the arguments for not using their social preview it's because it doesn't have a default image (logo) and default twitter title.
I've moved our social piece of code to be used when SEO checker is not available (fallback).
After this change go live, you need to enable it on the backoffice > seoChecker > settings > general settings > tab social > and enable twitter and facebook if it is the case.
After that, it will be automatically done. Attention, because you might need to review all pages created until now. Because they will probably need additions (image, title, ..).

If you prefer to remove the tab instead, let me know, it's a quick change.

**Comment by catiarodriguescosta** [comment]
Actually I found a way to user the title as a default twitter title and to facebook description. But they can be overridden with anything other text (and preview will be updated).
Also banner image is used as default to social image (for both twitter and facebook).

<img width="803" alt="Screenshot 2021-03-22 at 15 54 56" src="https://user-images.githubusercontent.com/34938764/112019515-69cd9c00-8b27-11eb-938c-ec206d708c02.png">

And about what I said before about seoChecker, you can ignore it. Once it's live, it should be fine, cause settings are controlled via git! :) So will close this issue.
