### ISSUE TITLE
SEO checker - Friendly links

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#17]
Add a block of text above the "Manage redirects" on the "Friendly links" tab.

> ## Redirects
> You only need to create a redirect if you need a friendly link, or if you've deleted a page and this replaces it.
>
> Friendly links are only for billboards. Otherwise, use the full link.
>
> For example, if another organisation is going to link to the page, use the full link and not a friendly link. This helps with our search rankings.

**Comment by mrmjprice** [comment]
> Update the SEO composition doctype so that manage redirects has that description above it
> @daylesalmon

**Comment by catiarodriguescosta** [comment]
<img width="1439" alt="Screenshot 2021-03-22 at 11 32 43" src="https://user-images.githubusercontent.com/34938764/111983750-5f4cdb80-8b02-11eb-8822-d3dff0b63b13.png">

Hey @mrmjprice, here it is. We are reusing a component created by Nathan probably (for major works) that's why it has the info icon. But it didn't look nonsense for this case. But if you have a different opinion let me know.

Reopen it if you need any other change! :)
