### ISSUE TITLE
SEO checker - Snippet preview doesn't update

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#18]
Snippet preview:
- [x] "The default SEO title properties will be used after first save." should be the page title
- [x] "/new-document" should be the page link

I also get the validation error:
- [x] The SEO Description meta tag for this page is empty.

**Comment by catiarodriguescosta** [comment]
About the first 2, actually, I don't see any issue with it because the file wasn't saved and that's how it works. If it happens after saving just refresh the page and it will be updated. Same when the override page title is populated, you'll need to save it and then it will update. By the other hand, SEO description is automatic. Anyway, I don't see it as something we can change... 

The last one is working fine now! :)
But I believe we will have a new validation error when the override page title is populated "about duplicated <title>" but you can ignore it.

<img width="1440" alt="Screenshot 2021-03-22 at 15 16 04" src="https://user-images.githubusercontent.com/34938764/112017612-ae583800-8b25-11eb-936e-8ba5235442a5.png">
