### ISSUE TITLE
File download component: Files are broken when downloaded

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#180]
## Describe the bug
PDF files that are attached to the file download component are broken when downloaded.

This issue has already been discussed and demoed to Catia.

Current pages which use this component:
* Local area maps: https://beta.wmnetwork.co.uk/plan-your-journey/discover-the-west-midlands/local-area-maps/
* Resources and support for businesses: https://beta.wmnetwork.co.uk/resources-and-support/resources-and-support-for-businesses/
* Swift and ticketing schemes https://beta.wmnetwork.co.uk/who-we-are/what-we-do/swift-and-ticketing-schemes/

**Comment by daylesalmon** [comment]
@jkmnch I've had a look into this issue...
I found a bug which has been resolved.

However, the core problem for this issue is that it is using the old file download **macro**, not the **component**.
You'll need to update all the file download macros on these pages to components by clicking on "add content" and then selecting the file download component.
![image](https://user-images.githubusercontent.com/13015201/121203452-04f42900-c86e-11eb-8ce3-15b29e07fccc.png)

I'll make sure in the next update that macros can't be added anymore as we aren't using them any more.

Let me know if you have any issues..

**Comment by jkmnch** [comment]
@daylesalmon Hey Dayle, these are the File Download components on the pages. I replaced the old macro file download with the new File Download components on the pages as Catia suggested yesterday. 

I tried it again today on the local area maps page and the files are still corrupted when downloaded

**Comment by daylesalmon** [comment]
Confirmed working with @jkmnch and will go live on Thursday.
