### ISSUE TITLE
Make beta phase banner a per-page setting

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#41]
Use case: Most of the site is live, but we're testing a new area.

**Comment by catiarodriguescosta** [comment]
_Some extra instructions:_
Section header: Beta banner
Control name: Show beta banner above content
Set control to **false by default**
The user will also need to be able to set the feedback survey link

The Default link for the feedback survey is this one: [https://surveys.hotjar.com/s?siteId=264586&surveyId=158308](https://surveys.hotjar.com/s?siteId=264586&surveyId=158308)
Note that if you are giving an external link please make sure you have the http/https otherwise he will assume it is an internal page -- that is applied to the wider website, not only on this specific case.

<img width="1432" alt="Screenshot 2021-03-05 at 16 34 18" src="https://user-images.githubusercontent.com/34938764/110145548-7638c180-7dd1-11eb-9209-ba36527a7b35.png">

Please reopen it, if you need any amend!
Thanks. :)

**Comment by catiarodriguescosta** [comment]
Actually, would be usefull to have what is the default link for the feedback survey visible on the backend?

**Comment by mrmjprice** [comment]
Hi @catiarodriguescosta

In most cases the user should submit their feedback about pages via the feedback loop in the footer.

The beta banner should be used if it the content is the start of a service.

For example, if there is a page of guidance before the user goes to a service.

So I don't think you need to specify a default link.

**Comment by catiarodriguescosta** [comment]
Okay, great!
My question now is, do you want to have the feedback survey link every time your page is beta?

**Comment by mrmjprice** [comment]
Yes, that needs to be mandatory

**Comment by catiarodriguescosta** [comment]
Perfect, then it's all good! Will close it!
