### ISSUE TITLE
Back Office landing page

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#45]
- [ ] Can we remove the Redirect URL Management tab?
- [ ] Could we iFrame the A-to-Z content guide into a tab

RE - A-to-Z, could possibly just take the page code from the design system and link the data to the live JSON file, so it stays up to date if we add/remove/change entries.

**Comment by mrmjprice** [comment]
This is for the /umbraco/#/content/ page btw

**Comment by catiarodriguescosta** [comment]
As everything that is edited outside the App_plugins folder vanishes with Umbraco updates, we have a file that does that for us inside the App_plugins folder. However, we shouldn't use it excessively otherwise there will cost us loading time.
I would remove the tab if that helps. But I'm not sure about adding a new tab for A-to-Z content guidelines. 
@daylesalmon I'll probably need your thoughts here?
